# name: Build and Push
# on:
#   push:
#     branches: [main]
# jobs:
#   build-and-push:
#     name: deploy to EC2
#     runs-on: self-hosted
#     steps:
#       - name: deploying
#         run: |
