name: Build and Push
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: self-hosted
    steps:
      - name: Build, Tag, and Push the Image to Amazon ECR
        run: |
          ./run.sh
