name: Build and Push
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: deploy to EC2
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: deploying
        run: |
        # "python3 app.py" to run
          ls
