name: Build and Push
on:
  push:
    branches: [main]
jobs:
  build-and-push:
    name: deploy to EC2
    runs-on: self-hosted
    steps:
      - name: deploying
        run: |
          git clone https://github.com/shanmukhchowdary147/devopstask2.git
          cd devopstask2
          git pull origin main
          python3 app.py
